# fly.toml app configuration file generated for node-fly-experimental on 2023-05-30T11:05:00+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "node-fly-experimental"
primary_region = "cdg"
